### ISSUE TITLE
Still a issue with some mods not downloading

### ISSUE THREAD

**Issue by Zemiox** [alec-hs/Flaxs-Arma-Server-Tool-2#124]
Mods for my server just seems to no download even one that i put on the workshop does not download and will not work.

https://steamcommunity.com/sharedfiles/filedetails/?id=2405397626 <-- my mod does not work
https://steamcommunity.com/sharedfiles/filedetails/?id=2161719492 <-- Another mod that will not work

These mods refresh fast but then nothing happens nothing is added.

**Comment by alec-hs** [comment]
Fixed - just not in latest release. Will be in next release.
