### ISSUE TITLE
Enabling Mods Not Working as Expected

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#18]
Enabling mods in the Server Side Mods adds the mods to -Mods= and not -serverMods=
Enabling mods in the Client Side Mods has no affect to the startup command

**Comment by alec-hs** [comment]
Added missing lines to separate server only mods from client required mods. Also made clearer in UI. Needs testing.

**Comment by JamieKG** [comment]
Tested and working as I think it is intended in Beta 5

**Comment by JamieKG** [comment]
Tested and working as I think it is intended in Beta 7
