### ISSUE TITLE
Mission Parameters For Each Mission

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#22]
Re asking for this in Fast 2 as I asked in Fast 1
Is it possible in Fast2 to add Mission Parameters for each mission in the server config so the %Servername%_config.cfg could look like this ?
```
class Missions
{
	class MyMission1
	{
		template="MyMission.Altis"
		difficulty="custom";
		class Params
		{
			myParam1=0;
			myParam2=0;
			myParam3=0;
		};
	};
	class MyMission2
	{
		template="MyMission.Tanoa"
		difficulty="custom";
		class Params
		{
			myParam1=0;
			myParam2=0;
			myParam3=0;
		};
	};
};
```
Thanks for the Tool
Thanks JamieKG

**Comment by JamieKG** [comment]
has extra new line in the server config
![image](https://user-images.githubusercontent.com/3878484/47934862-80301a00-ded0-11e8-8ac3-91abd6253942.png)

![image](https://user-images.githubusercontent.com/3878484/47934839-6f7fa400-ded0-11e8-8ab2-7b860329deac.png)

**Comment by alec-hs** [comment]
Confirmed working.
