### ISSUE TITLE
MaxMem and CPUCount Are Setting to 0

### ISSUE THREAD

**Issue by alec-hs** [alec-hs/Flaxs-Arma-Server-Tool-2#28]
These two values are defaulting to zero - they should stay blank.

**Comment by alec-hs** [comment]
Adjusted defaults.

**Comment by JamieKG** [comment]
Reset all Values button dose not clear the Fields but other then that its working fine on new profiles and ones I manually remove the values on

**Comment by alec-hs** [comment]
"Reset All Values" resets them to the BIS defaults rather than clearing the fields completely. Will make this clearer on the UI.

**Comment by alec-hs** [comment]
Original issues tested and fixed.
