### ISSUE TITLE
Open Last RTP and Delete Last RPT have not affect

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#29]
Open Last RTP and Delete Last RPT seem to have not affect also could the Delete last be delete All RPTs

**Comment by JamieKG** [comment]
just a update the server_console.log seems to be the same

**Comment by alec-hs** [comment]
All functionality now added - testing required.

**Comment by alec-hs** [comment]
Functionality works however causes crash if trying to delete RPT files when still in use by server. Need to add catch for files in use.

**Comment by JamieKG** [comment]
Complete
