### ISSUE TITLE
Formatting of multi line of Motd stops server from starting

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#31]
Formating of the motd stops the server from starting
```
motd[]= {
"Line 1
",
"Line 2",
};
```
I think should be 
```
motd[]= {
"Line 1",
"Line 2",
};
```

**Comment by alec-hs** [comment]
Added code to correctly format output to config. Testing required before closure.

**Comment by alec-hs** [comment]
Tested and working.
