### ISSUE TITLE
Mods Tab on Server Profile Has Broken Controls

### ISSUE THREAD

**Issue by alec-hs** [alec-hs/Flaxs-Arma-Server-Tool-2#33]
Currently the following controls do not do anything. They need to have code behind added/ edited. 

- [x]  Refresh Mods
- [x]  Copy/ Paste Selected

**Comment by alec-hs** [comment]
Copy and paste seems to cause issues with the lists removing. May add back at a later date.

**Comment by JamieKG** [comment]
complete
