### ISSUE TITLE
Multiple Admin UIDs Do Not Work

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#39]
Adding more then one admin UID crashes the server on launch.

_Originally posted by @JamieKG in https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2/issues/9#issuecomment-433135876_

**Comment by alec-hs** [comment]
Added code to correctly format output to config. Testing required before closure.

**Comment by alec-hs** [comment]
Tested and working.
