### ISSUE TITLE
Edits to server profile not saving

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool-2#50]
After creating my first server profile I needed to make a change for the HC ip address.  I made the change clicked on save and exited fast2.

When I restarted fast2 the server profile still had the original HC ip address and not the updated one.

**Comment by alec-hs** [comment]
@eric963  I cannot reproduce this - is this still happening for you?

**Comment by eric963** [comment]
I just deleted everything related to FAST2 and reinstalled and this issue is no there.
Thanks
Eric

**Comment by alec-hs** [comment]
Closing - not reproducible.
