### ISSUE TITLE
Can't download 'Large' mods

### ISSUE THREAD

**Issue by CALADARI** [alec-hs/Flaxs-Arma-Server-Tool-2#51]
When downloading large mode like RHS the download just quit without any info (since the progress function aren't added yet).And statue in steam mods indicated as 'Download not Complete'But it do downloads some smaller ones like CBA  & ACE3, all works fine.
Running FAST on Winserver 2012R2 with 20M bandwith.
Might be watchdog process force the download terminated(kinda fake timeout)?Just a guess, I'm not a programmer tho :D

- Log in console as below

Steam Console Client (c) Valve Corporation-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user '_MySteamAccount_' to Steam Public...

Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:Logged in OK
Waiting for user info...OK

Downloading item 843425103 (it's RHSAFRF)  ..
SteamCMD Exited

**Comment by alec-hs** [comment]
This is caused by a SteamCMD download timeout - something I cannot change in FAST. The documentation on SteamCMD is minimal so finding the cause/ fix is near impossible. 

 If you retry a couple of time the download should complete.  Let me know if the download continuously fails after a few retries. This generally happens with slower connections like yours - I do not get time outs but I have a 500Mbps and a 1Gbps connection on my test servers.

**Comment by CALADARI** [comment]
> This is caused by a SteamCMD download timeout - something I cannot change in FAST. The documentation on SteamCMD is minimal so finding the cause/ fix is near impossible.
> 
> If you retry a couple of time the download should complete. Let me know if the download continuously fails after a few retries. This generally happens with slower connections like yours - I do not get time outs but I have a 500Mbps and a 1Gbps connection on my test servers.

Many thanks I'll surely try it out and inform ya(it late here in my time zone so that'll be hours later). If it keep happening I'll use offline(local) mods instead, not a big deal. Thanks for the work, keep it up :D.
Maybe u could add a auto-retry in FAST and then time it out in FAST after few trial with message with 'Fail or having trouble downloading mod -xxxxxx due to poor/no network with steam, plz use offline method or keep retrying.' and skip to next mod that might okay with downloading.

**Comment by CALADARI** [comment]
> > This is caused by a SteamCMD download timeout - something I cannot change in FAST. The documentation on SteamCMD is minimal so finding the cause/ fix is near impossible.
> > If you retry a couple of time the download should complete. Let me know if the download continuously fails after a few retries. This generally happens with slower connections like yours - I do not get time outs but I have a 500Mbps and a 1Gbps connection on my test servers.
> 

And yes,confirmed RHS finished downloading after few trial. Should be steamCMD timed out the downloading process as what u described.
Suggest adding auto retry as mentioned in last reply , since not everyone can afford a high perform server like with 500Mbps bandwidth ;D (Sooooo jealousy, thats  even 5 times faster than my personal network 🤦‍♂️ )

**Comment by alec-hs** [comment]
Haha yeah you'd be surprised how cheap it is - I pay about £30 a month for an i7-3770 16GB RAM and the 500Mbps connection with unlimited usage. 

Auto-rety mod downloads is on the todo list but might not be in until v2.2.

**Comment by CALADARI** [comment]
> Haha yeah you'd be surprised how cheap it is - I pay about £30 a month for an i7-3770 16GB RAM and the 500Mbps connection with unlimited usage.
> 
> Auto-retry mod downloads is on the todo list but might not be in until v2.2.

Whoa that's really a bargain , I paid about 34GBP(transferred) for a 16core 16GB server but with poor network :(
But mine is commercial server so price is pretty fair (DDOS defense,static IP,registered domain etc.)  I don't have a better solution right now ...
Do tried using my retried PC for sever but maintenance is too troublesome,especially in a country with dynamic IP so need extra charge for static one and I'm undergraduate far from home and with heavy lessons to attend.
Thx for reply & attention anyway , enjoy chatting with ya and I'll keep eyes on any issue i encounter,gl mate, have a nice day(or evening maybe?)
