### ISSUE TITLE
Language issue & FAST crash on start & MKLINK issue

### ISSUE THREAD

**Issue by CALADARI** [alec-hs/Flaxs-Arma-Server-Tool-2#52]
Some of my mods was repacked by myself and thus name contains Chinese characters(Dunno if other non-English character would have same issue).
The name,workshop ID all info in 'steam mod' page works fine & no problem with downloading.
workshop ID list below just in case u need
- 1270303699 for TRS功能性整合(Functional Enhancement) a package with Ares repacked etc.
- 1570122738 for TRS装备包(Gear Pack) repackage of few gear mods.

So as I comprehend the FAST will automatically create a hardlink in server folder named after the name fetch from workshop(if its from meta.cpp then might explains sth, see below) for each mod downloaded by steamCMD.
I do think issue start from this process.
1. The steamCMD downloaded the mod and named it after the workshop ID(Checked both folder ,confirmed integrated), all good except a minor issue I mention below.
2. FAST reads the mod's name & create a hardlink for it, but for some reason the FAST doesn't recognize the Chinese  characters and thus named the shortcut as '@TRS__' .![only one folder with wrong name](https://user-images.githubusercontent.com/45614593/49843914-d3648900-fdfb-11e8-992c-327b099c6ab1.png)
For comparison,image from my '!workshop' floder:![image](https://user-images.githubusercontent.com/45614593/49843957-fa22bf80-fdfb-11e8-9edf-8ce3bf3f6358.png)

3. Since both mod are started with 'TRS' so the FAST only created one folder (in mine situation its hardlink for 1570122738, maybe that's because after one covered the prev one cuze the same name? )
4. I found the issue when setting up server config in 'server setting' page. That's not a big deal, I can fix it myself, So I just rename the mistaken hardlink the correct name and wanna check if FAST identify the floder with new name, if all good I'll just import another missing folder as local mod.
5. Then FAST start crashing on start, report pasted below.
问题签名:
  问题事件名称(Issue name):	CLR20r3
  问题签名（Issue signature） 01:	FAST2.exe
  问题签名 02:	2.0.1.2
  问题签名 03:	5c0e5232
  问题签名 04:	System.Xaml
  问题签名 05:	4.7.3081.0
  问题签名 06:	5b1890f2
  问题签名 07:	81d
  问题签名 08:	a
  问题签名 09:	System.Windows.Markup.XamlParse
  OS 版本(Version):	6.3.9600.2.0.0.400.8
  区域设置(Location setting) ID:	2052
  其他信息(Other info) 1:	5861
  其他信息 2:	5861822e1919d7c014bbb064c64908b2
  其他信息 3:	a10f
  其他信息 4:	a10ff7d2bb2516fdc753f9c34fc3b069
6. So I tried delete FAST2 folder & re-install FAST , still crashing 
but rep with Issue Signature 04 :   mscorlib

One thing is I checked the meta.cpp & mod.cpp in workshop\content\ ,seems corrupted, all Chinese characters goes messy. But not for those downloaded by steam on my own PC(I'm su
re not related to system coding cuze my Win10 & the server are using the same, seems another issue related to steamCMD, bah.).

Don't have any solution nw, it just crash on start, FAST is the best server starter I ever used, I might use the old TADST temporally. Upload the error-causing mod by other method & import them in FAST as local mod looks like able to solve the problem for now so  maybe I'll just backup all saving files on my DayZ server and then re-install the server's operating system for FAST :(.

I also just find problem with hardlinks creation , FAST didn't create link for mods upgraded using the standalone button(beside the delete button u know) , 32 mods in total(107410 folder) but link in server folder are only 30 folders(I already fixed some by mklink /j by myself, i realized it's FAST issue a while after).

**Comment by CALADARI** [comment]
Btw i found a same issue in DayZ, seems steamCMD are not so friendly to some(particular?) .cpps(but the cpp seems like a data file steam itself,will look into it later)
It hops out a error like few mods in ArmA3, Sadly thats Valves stuff that we cant do much,just reporting cuze i think you should informed.Screenshot pasted below.(Sadly I know little on VB so I cant help with the project, I'm now learning C# :P)

![default](https://user-images.githubusercontent.com/45614593/50064962-ef4a9f00-01ee-11e9-9764-54181a4c782e.PNG)

**Comment by alec-hs** [comment]
@CALADARI whilst I will try and fix the language issue in future I a going to close this for now. 

I would suggest you remove those workshop mods you have uploaded as you are breaking the Steam Workshop agreement and I doubt you have permission from the original authors to repack their work.
