### ISSUE TITLE
Disabling voting with no mission rotation can result in infinite load screen when connecting

### ISSUE THREAD

**Issue by Tommo-S** [alec-hs/Flaxs-Arma-Server-Tool-2#53]
Hi,

I wanted to use FAST2 to set up a testing environment and manage mods for a dedi + a single HC and ran into this issue.

If you disable voting in FAST2, it will still insert the current minimum players value into the server config file. The default option is voteMissionPlayers = 3;. If you do disable voting, and didn't define a mission rotation, when you connect to the dedicated server, you will see a loading screen that lasts until the minimum players connect to show the mission vote screen. Trying to log in manually as admin didn't resolve the issue.

Could you add a warning, or automatically lower voteMissionplayers to 1 when voting is disabled?

Thanks.

**Comment by alec-hs** [comment]
Not a bug - will adjust UI and options to inform users that these values can cause issues.

**Comment by alec-hs** [comment]
See #94 - Voting refactor should have this fixed.
