### ISSUE TITLE
Steam password with spaces needs quotes around it.

### ISSUE THREAD

**Issue by billw2012** [alec-hs/Flaxs-Arma-Server-Tool-2#59]
Title! I was getting password incorrect, but if I add quotes around my password that contains spaces, it works fine. Same if I do steam cmd command line so I guess you are going the same. It should be fine to just always put quotes around the password when generating the command line I expect.

**Comment by alec-hs** [comment]
Will fix but generally a bad idea to have spaces in your passwords, as proven here you can't really rely on space being a valid character when it goes though validation etc.
