### ISSUE TITLE
Headless client not connecting on ports other than 2302

### ISSUE THREAD

**Issue by Cytreen** [alec-hs/Flaxs-Arma-Server-Tool-2#61]
When ever you have a server on a port other than 2302, the headless clients will not connect when launching a server. We need this kind of functionality as we run multiple server at the same time on our box.
Tested Ports
2312
2402
2502

**Comment by nobodyshome** [comment]
Second this. Just came across the issue with my setup. Could only get the Headless Clients to connect on servers with ports 2302.

**Comment by alec-hs** [comment]
Can't reproduce this - seems to work fine on my test.
![image](https://user-images.githubusercontent.com/6503411/85208394-f4c6ff00-b327-11ea-8142-8c05e045a9e3.png)
