### ISSUE TITLE
FAST is stuck when steam sends new auth code

### ISSUE THREAD

**Issue by kju** [alec-hs/Flaxs-Arma-Server-Tool-2#72]
Could be same or related to #64 #20 #42 

**Observed**:

- FAST is stuck endless in the updating process.
- You get many emails from Steam with the AUTH code.
- You get temp banned by Steam due to this.

**Expected**:

- FAST has a timeout for the updating process.
- FAST stops when Steam requests AUTH code.
- Optional: Allows to enter the AUTH code in a pop up.

**Note**: Didnt see anywhere in settings/options to enter the AUTH code (or to change the Steam details) - maybe i am blind though :D

Repro:

1. You install FAST on a new server.
2. You install steamCMD.
3. You run FAST, enter the Steam account details.
4. You try to update/download Arma 3.
5. FAST is stuck endless in the updating process.

**Comment by GhostJumper** [comment]
Temporary soulution:
https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2/issues/64

https://www.dropbox.com/s/ct02apkejk7man5/FAST2.exe?dl=0
