### ISSUE TITLE
Creates broken basic.cfg

### ISSUE THREAD

**Issue by DragonGER** [alec-hs/Flaxs-Arma-Server-Tool-2#74]
After some big troubbles setting up my server i found out
that F.A.S.T is generating wrong basic.cfg files effectively breaking arma3 netcode.

The Problem in detail:

"MinErrorToSend=0,01;" is wrong because arma does understand ","
Arma can only parse float numbers when written with a ".".
Correct Version should be "MinErrorToSend=0.01;"

Here you can see what happens as a result to that error:
https://youtu.be/yt_IUOaeAPw

**Comment by mikaelssen** [comment]
Holy shit i was stuck at this for days. thanks!

**Comment by alec-hs** [comment]
Decimal points should be written with "." not "," I will put code in to replace "," with "." European system of 1.000,00 is incorrect, it should be 1,000.00
