### ISSUE TITLE
Server Voting Issue

### ISSUE THREAD

**Issue by MontyBravo** [alec-hs/Flaxs-Arma-Server-Tool-2#75]
When Enabeling Voting you cannot edit vote commands in,  upon launch or save it is automatically defaulted to ' ={}; ' This disables all the voteing commands.

Yet disabling Voting removes ' ={}; ' therefore enabling them all.

**Comment by Drift91** [comment]
The little "switch" button is kind of backwards and confusing. Normally you'd expect the switch being on would enable a feature. However the switch is labelled as "disable voting" so turning the switch on disables it. I got confused at first too until I noticed the "disable voting" tooltip.
