### ISSUE TITLE
FAST crashes when using update all mods

### ISSUE THREAD

**Issue by TomTucka** [alec-hs/Flaxs-Arma-Server-Tool-2#79]
Currently FAST will crash when you try to update all mods... this is due to the method below:

`UpdateMod(modId As Int32, modName As String, Optional singleMod As Boolean = True)`

pretty sure the culprit line is: `linkPath = My.Settings.serverPath & "\@" & Functions.SafeName(modName)`

best fix for this would be to engineer the use of `modName` out

**Comment by diveyez** [comment]
Yeah. It seems so. The entire program started to crash out on me this past week when simply starting it after windows updates. Had to reset FAST and lose all the profiles. =/

**Comment by TomTucka** [comment]
I'm working on a contribution to fix some of these issues, haven't touched vb for years. hoping to get this sorted for the weekend

**Comment by Drift91** [comment]
Is this perhaps a duplicate of #58? Or an entirely different issue?

Either way, glad to know you guys have found the cause and a possible solution.

**Comment by Drift91** [comment]
For those of you who haven't joined the Kestrel Studios Discord or checked out the forks, there's an actively developed fork being worked on:
https://github.com/Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite/releases

Flax is still alive btw, just been busy enjoying his vacation.

**Comment by alec-hs** [comment]
Closing as duplicate of #58
