### ISSUE TITLE
FAST2 insists that Workshop mod is from another game and refuses to add it to list of steam mods

### ISSUE THREAD

**Issue by Drift91** [alec-hs/Flaxs-Arma-Server-Tool-2#80]
For some reason when I try to add the below mod via a launcher preset nothing happens and then when I try to add it individually it gives an error stating that the workshop item belongs to another game. I suspect it may have something to do with the mod requiring the Helicopters DLC.

Mod in question: https://steamcommunity.com/sharedfiles/filedetails/?id=286579896

**Comment by McfarlaneRob** [comment]
I have also run into this issue, but it is affecting all of the mods in my list of around 30.
Below is the console output that is given when installing one mod

Logged in OK

Waiting for user info...OK

Downloading item 1964186045 ...

ERROR! Download item 1964186045 failed (Failure).Redirecting stderr to 'G:\Apps\Steam\logs\stderr.txt'

[  0%] Checking for available updates...

[----] Verifying installation...

SteamCMD Exited
