### ISSUE TITLE
Can't add mods from workshop "Cannot reach Steam API"

### ISSUE THREAD

**Issue by TheSecretBadger** [alec-hs/Flaxs-Arma-Server-Tool-2#81]
Logging in and installing the server works fine, but when I try to add mods either through a link or an export file I get this error.

![bb3cb1c4b206d0d4b78cf5c5de42ed68](https://user-images.githubusercontent.com/53126993/72739992-b5d82600-3b9c-11ea-8708-2992d18d2f97.png)

**Comment by alec-hs** [comment]
Issue caused by me accidentally revoking Steam API key. Will create fix asap.
