### ISSUE TITLE
Mission folder

### ISSUE THREAD

**Issue by SonycCZE** [alec-hs/Flaxs-Arma-Server-Tool-2#85]
Hi, i have successfully setup AMRA3 FAST2 server but no mission under "Missions + Client" card is showed. I put my /mission_name/mission.sqm to ARMA3 server "mpmissions" folder but nothing showed up... any help where i need to put my mission (in vanilla server mission works well).
Thanks.

**Comment by SonycCZE** [comment]
Well, if i write custom mission class it works well with mpmissions folder in ARMA3 server :).

**Comment by TomTucka** [comment]
@SonycCZE can you send me the custom mission class you wrote?
