### ISSUE TITLE
Add and Update Missing/ Changed Server Params

### ISSUE THREAD

**Issue by alec-hs** [alec-hs/Flaxs-Arma-Server-Tool-2#9]
Below are the params that need adding/ updating. Please comment with anymore as you find/ notice them. 

**TO DO**

- [x] maxMem
- [x] cpuCount
- [x] filePatching - currently set twice in performance + scripting?

**Comment by warzen** [comment]
Many custom settings are not binary:
	/* Situational awareness */
	groupIndicators = 0;		// Group indicators (0 = never, 1 = limited distance, 2 = always)
	friendlyTags = 0;		// Friendly name tags (0 = never, 1 = limited distance, 2 = always)
	enemyTags = 0;			// Enemy name tags (0 = never, 1 = limited distance, 2 = always)
	detectedMines = 0;		// Detected mines (0 = never, 1 = limited distance, 2 = always)
	commands = 1;			// Commands (0 = never, 1 = fade out, 2 = always)
	waypoints = 1;			// Waypoints (0 = never, 1 = fade out, 2 = always)

	/* Personal awareness */
	weaponInfo = 2;			// Weapon info (0 = never, 1 = fade out, 2 = always)
	stanceIndicator = 2;		// Stance indicator (0 = never, 1 = fade out, 2 = always)

cf https://community.bistudio.com/wiki/server.armaprofile

**Comment by JamieKG** [comment]
you can add admins to the server.cfg would be cool to see that added 
admins[] = {"<UID>"}; 
https://community.bistudio.com/wiki/server.cfg#Server_Options

**Comment by alec-hs** [comment]
File patching is supposed to be there twice - one the Perf and Scripting tab it relates to the server having file patching turned on. On the Settings tab it refers to the setting that allows or disallows file patching on the clients. 

Max Memory, CPU Count and Admin UID's have been added. Testing needed.

**Comment by alec-hs** [comment]
Corrected all non binary options for the custom difficulty. Testing needed.

**Comment by JamieKG** [comment]
complete

**Comment by JamieKG** [comment]
scratch my last comment I -filePatching a client option that need to be only added to the HC ?

**Comment by alec-hs** [comment]
> File patching is supposed to be there twice - one the Perf and Scripting tab it relates to the server having file patching turned on. On the Settings tab it refers to the setting that allows or disallows file patching on the clients.
> 

See above comment for filePatching.

**Comment by alec-hs** [comment]
All missing params added and tested. Additional issues opened for child bugs.
