### ISSUE TITLE
Download Link is Not Latest Master Version

### ISSUE THREAD

**Issue by PatriotRDX** [alec-hs/Flaxs-Arma-Server-Tool-2#92]
The download link [here](https://deploy.kestrelstudios.co.uk/updates/FAST2/FAST2-latest.zip) for the latest installable version is not up to date with the current version of master.

**Comment by alec-hs** [comment]
The one on the deploy server is tested and fixed - master branch hasn't been "built" and uploaded yet. Expect a new build on the auto-updater by start of next week.
